# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ai_robot_rctl_server/RctlMapMetaData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import nav_msgs.msg
import std_msgs.msg

class RctlMapMetaData(genpy.Message):
  _md5sum = "b49a4f33aa8f12c7f46b99506f489601"
  _type = "ai_robot_rctl_server/RctlMapMetaData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String name
nav_msgs/MapMetaData data

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: nav_msgs/MapMetaData
# This hold basic information about the characterists of the OccupancyGrid

# The time at which the map was loaded
time map_load_time
# The map resolution [m/cell]
float32 resolution
# Map width [cells]
uint32 width
# Map height [cells]
uint32 height
# The origin of the map [m, m, rad].  This is the real-world pose of the
# cell (0,0) in the map.
geometry_msgs/Pose origin
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['name','data']
  _slot_types = ['std_msgs/String','nav_msgs/MapMetaData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RctlMapMetaData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = std_msgs.msg.String()
      if self.data is None:
        self.data = nav_msgs.msg.MapMetaData()
    else:
      self.name = std_msgs.msg.String()
      self.data = nav_msgs.msg.MapMetaData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2If2I7d().pack(_x.data.map_load_time.secs, _x.data.map_load_time.nsecs, _x.data.resolution, _x.data.width, _x.data.height, _x.data.origin.position.x, _x.data.origin.position.y, _x.data.origin.position.z, _x.data.origin.orientation.x, _x.data.origin.orientation.y, _x.data.origin.orientation.z, _x.data.origin.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.name is None:
        self.name = std_msgs.msg.String()
      if self.data is None:
        self.data = nav_msgs.msg.MapMetaData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name.data = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.data.map_load_time.secs, _x.data.map_load_time.nsecs, _x.data.resolution, _x.data.width, _x.data.height, _x.data.origin.position.x, _x.data.origin.position.y, _x.data.origin.position.z, _x.data.origin.orientation.x, _x.data.origin.orientation.y, _x.data.origin.orientation.z, _x.data.origin.orientation.w,) = _get_struct_2If2I7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2If2I7d().pack(_x.data.map_load_time.secs, _x.data.map_load_time.nsecs, _x.data.resolution, _x.data.width, _x.data.height, _x.data.origin.position.x, _x.data.origin.position.y, _x.data.origin.position.z, _x.data.origin.orientation.x, _x.data.origin.orientation.y, _x.data.origin.orientation.z, _x.data.origin.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.name is None:
        self.name = std_msgs.msg.String()
      if self.data is None:
        self.data = nav_msgs.msg.MapMetaData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name.data = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.data.map_load_time.secs, _x.data.map_load_time.nsecs, _x.data.resolution, _x.data.width, _x.data.height, _x.data.origin.position.x, _x.data.origin.position.y, _x.data.origin.position.z, _x.data.origin.orientation.x, _x.data.origin.orientation.y, _x.data.origin.orientation.z, _x.data.origin.orientation.w,) = _get_struct_2If2I7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2If2I7d = None
def _get_struct_2If2I7d():
    global _struct_2If2I7d
    if _struct_2If2I7d is None:
        _struct_2If2I7d = struct.Struct("<2If2I7d")
    return _struct_2If2I7d
