// Generated by gencpp from file ai_robot_interfaces/MpTraj.msg
// DO NOT EDIT!


#ifndef AI_ROBOT_INTERFACES_MESSAGE_MPTRAJ_H
#define AI_ROBOT_INTERFACES_MESSAGE_MPTRAJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>
#include <nav_msgs/Path.h>

namespace ai_robot_interfaces
{
template <class ContainerAllocator>
struct MpTraj_
{
  typedef MpTraj_<ContainerAllocator> Type;

  MpTraj_()
    : map_points()
    , trajectory()  {
    }
  MpTraj_(const ContainerAllocator& _alloc)
    : map_points(_alloc)
    , trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PointStamped_<ContainerAllocator> >> _map_points_type;
  _map_points_type map_points;

   typedef  ::nav_msgs::Path_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> const> ConstPtr;

}; // struct MpTraj_

typedef ::ai_robot_interfaces::MpTraj_<std::allocator<void> > MpTraj;

typedef boost::shared_ptr< ::ai_robot_interfaces::MpTraj > MpTrajPtr;
typedef boost::shared_ptr< ::ai_robot_interfaces::MpTraj const> MpTrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ai_robot_interfaces::MpTraj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ai_robot_interfaces::MpTraj_<ContainerAllocator1> & lhs, const ::ai_robot_interfaces::MpTraj_<ContainerAllocator2> & rhs)
{
  return lhs.map_points == rhs.map_points &&
    lhs.trajectory == rhs.trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ai_robot_interfaces::MpTraj_<ContainerAllocator1> & lhs, const ::ai_robot_interfaces::MpTraj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ai_robot_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c82395b8bdda0452a5f88bde8d1b1a0";
  }

  static const char* value(const ::ai_robot_interfaces::MpTraj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c82395b8bdda045ULL;
  static const uint64_t static_value2 = 0x2a5f88bde8d1b1a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ai_robot_interfaces/MpTraj";
  }

  static const char* value(const ::ai_robot_interfaces::MpTraj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PointStamped[] map_points\n"
"nav_msgs/Path trajectory\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ai_robot_interfaces::MpTraj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_points);
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MpTraj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ai_robot_interfaces::MpTraj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ai_robot_interfaces::MpTraj_<ContainerAllocator>& v)
  {
    s << indent << "map_points[]" << std::endl;
    for (size_t i = 0; i < v.map_points.size(); ++i)
    {
      s << indent << "  map_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.map_points[i]);
    }
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AI_ROBOT_INTERFACES_MESSAGE_MPTRAJ_H
