// Generated by gencpp from file ai_robot_interfaces/restart_nav.msg
// DO NOT EDIT!


#ifndef AI_ROBOT_INTERFACES_MESSAGE_RESTART_NAV_H
#define AI_ROBOT_INTERFACES_MESSAGE_RESTART_NAV_H

#include <ros/service_traits.h>


#include <ai_robot_interfaces/restart_navRequest.h>
#include <ai_robot_interfaces/restart_navResponse.h>


namespace ai_robot_interfaces
{

struct restart_nav
{

typedef restart_navRequest Request;
typedef restart_navResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct restart_nav
} // namespace ai_robot_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ai_robot_interfaces::restart_nav > {
  static const char* value()
  {
    return "84f711453560507221d036b9e0cffe3b";
  }

  static const char* value(const ::ai_robot_interfaces::restart_nav&) { return value(); }
};

template<>
struct DataType< ::ai_robot_interfaces::restart_nav > {
  static const char* value()
  {
    return "ai_robot_interfaces/restart_nav";
  }

  static const char* value(const ::ai_robot_interfaces::restart_nav&) { return value(); }
};


// service_traits::MD5Sum< ::ai_robot_interfaces::restart_navRequest> should match
// service_traits::MD5Sum< ::ai_robot_interfaces::restart_nav >
template<>
struct MD5Sum< ::ai_robot_interfaces::restart_navRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ai_robot_interfaces::restart_nav >::value();
  }
  static const char* value(const ::ai_robot_interfaces::restart_navRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ai_robot_interfaces::restart_navRequest> should match
// service_traits::DataType< ::ai_robot_interfaces::restart_nav >
template<>
struct DataType< ::ai_robot_interfaces::restart_navRequest>
{
  static const char* value()
  {
    return DataType< ::ai_robot_interfaces::restart_nav >::value();
  }
  static const char* value(const ::ai_robot_interfaces::restart_navRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ai_robot_interfaces::restart_navResponse> should match
// service_traits::MD5Sum< ::ai_robot_interfaces::restart_nav >
template<>
struct MD5Sum< ::ai_robot_interfaces::restart_navResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ai_robot_interfaces::restart_nav >::value();
  }
  static const char* value(const ::ai_robot_interfaces::restart_navResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ai_robot_interfaces::restart_navResponse> should match
// service_traits::DataType< ::ai_robot_interfaces::restart_nav >
template<>
struct DataType< ::ai_robot_interfaces::restart_navResponse>
{
  static const char* value()
  {
    return DataType< ::ai_robot_interfaces::restart_nav >::value();
  }
  static const char* value(const ::ai_robot_interfaces::restart_navResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AI_ROBOT_INTERFACES_MESSAGE_RESTART_NAV_H
