// Generated by gencpp from file ai_robot_interfaces/restart_navResponse.msg
// DO NOT EDIT!


#ifndef AI_ROBOT_INTERFACES_MESSAGE_RESTART_NAVRESPONSE_H
#define AI_ROBOT_INTERFACES_MESSAGE_RESTART_NAVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ai_robot_interfaces
{
template <class ContainerAllocator>
struct restart_navResponse_
{
  typedef restart_navResponse_<ContainerAllocator> Type;

  restart_navResponse_()
    : set_ok(false)  {
    }
  restart_navResponse_(const ContainerAllocator& _alloc)
    : set_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _set_ok_type;
  _set_ok_type set_ok;





  typedef boost::shared_ptr< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> const> ConstPtr;

}; // struct restart_navResponse_

typedef ::ai_robot_interfaces::restart_navResponse_<std::allocator<void> > restart_navResponse;

typedef boost::shared_ptr< ::ai_robot_interfaces::restart_navResponse > restart_navResponsePtr;
typedef boost::shared_ptr< ::ai_robot_interfaces::restart_navResponse const> restart_navResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator1> & lhs, const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator2> & rhs)
{
  return lhs.set_ok == rhs.set_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator1> & lhs, const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ai_robot_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea821051b80d6301bad612e03b952799";
  }

  static const char* value(const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea821051b80d6301ULL;
  static const uint64_t static_value2 = 0xbad612e03b952799ULL;
};

template<class ContainerAllocator>
struct DataType< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ai_robot_interfaces/restart_navResponse";
  }

  static const char* value(const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool set_ok\n"
"\n"
;
  }

  static const char* value(const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.set_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct restart_navResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ai_robot_interfaces::restart_navResponse_<ContainerAllocator>& v)
  {
    s << indent << "set_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AI_ROBOT_INTERFACES_MESSAGE_RESTART_NAVRESPONSE_H
