// Generated by gencpp from file ai_robot_interfaces/set_destination.msg
// DO NOT EDIT!


#ifndef AI_ROBOT_INTERFACES_MESSAGE_SET_DESTINATION_H
#define AI_ROBOT_INTERFACES_MESSAGE_SET_DESTINATION_H

#include <ros/service_traits.h>


#include <ai_robot_interfaces/set_destinationRequest.h>
#include <ai_robot_interfaces/set_destinationResponse.h>


namespace ai_robot_interfaces
{

struct set_destination
{

typedef set_destinationRequest Request;
typedef set_destinationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_destination
} // namespace ai_robot_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ai_robot_interfaces::set_destination > {
  static const char* value()
  {
    return "e4fcf36e5fed223dc6e0551e5302eab7";
  }

  static const char* value(const ::ai_robot_interfaces::set_destination&) { return value(); }
};

template<>
struct DataType< ::ai_robot_interfaces::set_destination > {
  static const char* value()
  {
    return "ai_robot_interfaces/set_destination";
  }

  static const char* value(const ::ai_robot_interfaces::set_destination&) { return value(); }
};


// service_traits::MD5Sum< ::ai_robot_interfaces::set_destinationRequest> should match
// service_traits::MD5Sum< ::ai_robot_interfaces::set_destination >
template<>
struct MD5Sum< ::ai_robot_interfaces::set_destinationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ai_robot_interfaces::set_destination >::value();
  }
  static const char* value(const ::ai_robot_interfaces::set_destinationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ai_robot_interfaces::set_destinationRequest> should match
// service_traits::DataType< ::ai_robot_interfaces::set_destination >
template<>
struct DataType< ::ai_robot_interfaces::set_destinationRequest>
{
  static const char* value()
  {
    return DataType< ::ai_robot_interfaces::set_destination >::value();
  }
  static const char* value(const ::ai_robot_interfaces::set_destinationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ai_robot_interfaces::set_destinationResponse> should match
// service_traits::MD5Sum< ::ai_robot_interfaces::set_destination >
template<>
struct MD5Sum< ::ai_robot_interfaces::set_destinationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ai_robot_interfaces::set_destination >::value();
  }
  static const char* value(const ::ai_robot_interfaces::set_destinationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ai_robot_interfaces::set_destinationResponse> should match
// service_traits::DataType< ::ai_robot_interfaces::set_destination >
template<>
struct DataType< ::ai_robot_interfaces::set_destinationResponse>
{
  static const char* value()
  {
    return DataType< ::ai_robot_interfaces::set_destination >::value();
  }
  static const char* value(const ::ai_robot_interfaces::set_destinationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AI_ROBOT_INTERFACES_MESSAGE_SET_DESTINATION_H
