(cl:defpackage ai_robot_interfaces-srv
  (:use )
  (:export
   "RESTART_NAV"
   "<RESTART_NAV-REQUEST>"
   "RESTART_NAV-REQUEST"
   "<RESTART_NAV-RESPONSE>"
   "RESTART_NAV-RESPONSE"
   "SET_DESTINATION"
   "<SET_DESTINATION-REQUEST>"
   "SET_DESTINATION-REQUEST"
   "<SET_DESTINATION-RESPONSE>"
   "SET_DESTINATION-RESPONSE"
  ))

